dist: bionic
language: cpp
sudo: require

compiler:
  -gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq lcov gcovr

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make

after_success:
#Run code
  - ./main/gtestExample1_run 
#Cpp check
  - cppcheck --quiet --force --error-exitcode=1 .
#Run google test
  - ./test/gtestExample1_tst 
#Run code coverage
  - sh ../code_cov.sh
